[project]
name = "train-catcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.1",
    "pytz>=2025.2",
    "stomp-py>=8.2.0",
]
